Uptycs/cloudquery

- utilities/type_converters.go
- utilities/utilities_test.go
Reduce the cyclomatic complexity in functions that convert arbitrary value to string.
Remove unused functions.
NA
Added new test cases to verify getStringValue()
> Reduce cyclomatic complexity in type_converters.go

- utilities/table.go
Reduce cyclo complexity in flattenValue of tables.go
NA
Ran all unit tests
> reduce cyclo complexity in flattenValue

- utilities/table.go
reduce cyclo complexity in flattenValue. take 2
NA
Ran all unit-tests
> reduce cyclo complexity in flattenValue. take 2

- cmd/cloudquery/main.go
- extension/helper.go
Logger is not getting initialize with configured path and other settings.
NA
Tested with osqueryi
Log file is getting created in configured location
> Init logger after config file is read

- extension/aws/iam/aws_iam_account_password_policy.go
- extension/aws/iam/table_config.json
- extension/aws/iam/tables.md
- extension/aws/tables.md
- extension/helper.go
Add new table: aws_iam_account_password_policy
Tested using osqueryi
> Add aws_iam_account_password_policy table

- .github/workflows/codeql-analysis.yml
- .github/workflows/go.yml
- It's better to set GOPATH for fossa-cli
- It's better to do the actual build for CodeQL
Apart from these, I've unified the style of the workflow, but if you don't like it, I can revert it.
> Update GitHub Actions workflows

- extension/aws/acm/aws_acm_certificate.go
- extension/aws/acm/table_config.json
- extension/aws/acm/tables.md
- extension/aws/tables.md
- extension/helper.go
Added ACM tables
Tests done using osqueryi
> acm tables

- extension/aws/acm/aws_acm_certificate.go
- extension/aws/cloudwatch/aws_cloudwatch_alarm.go
- extension/aws/cloudwatch/aws_cloudwatch_event_bus.go
- extension/aws/cloudwatch/aws_cloudwatch_event_rule.go
- extension/aws/config/aws_config_delivery_channel.go
- extension/aws/config/aws_config_recorder.go
- extension/aws/ec2/aws_ec2_address.go
- extension/aws/ec2/aws_ec2_egress_only_internet_gateway.go
- extension/aws/ec2/aws_ec2_flowlog.go
- extension/aws/ec2/aws_ec2_image.go
- extension/aws/ec2/aws_ec2_instance.go
- extension/aws/ec2/aws_ec2_internet_gateway.go
- extension/aws/ec2/aws_ec2_keypair.go
- extension/aws/ec2/aws_ec2_nat_gateway.go
- extension/aws/ec2/aws_ec2_network_acl.go
- extension/aws/ec2/aws_ec2_route_table.go
- extension/aws/ec2/aws_ec2_security_group.go
- extension/aws/ec2/aws_ec2_snapshot.go
- extension/aws/ec2/aws_ec2_subnet.go
- extension/aws/ec2/aws_ec2_tag.go
- extension/aws/ec2/aws_ec2_volume.go
- extension/aws/ec2/aws_ec2_vpc.go
Ignore region error and continue to next region
Sanity test usign osqueryi
> Ignore region errors.

- extension/event_table.go
- extension/gcp/cloudlog/gcp_cloud_log_event.go
- extension/gcp/cloudlog/table_config.json
- extension/helper.go
- utilities/extension_configuration.go
Support GCP audit logs (an events) table
NA
Tested with GCP audit logs enabled at Project Level.
Routed logs to Cloud Storage Sink (a storage bucket).
> Support for GCP cloud log event table

- Dockerfile
Docker container does't have some config tables for newly added tables.
There are error logs showing the missing files
Tested with docker image built locally.
> Modify Docker file to add missing config dirs

- Dockerfile
- extension/gcp/compute/gcp_compute_disk.go
- extension/gcp/compute/gcp_compute_image.go
- extension/gcp/compute/gcp_compute_instance.go
- extension/gcp/compute/gcp_compute_interconnect.go
- extension/gcp/compute/gcp_compute_network.go
- extension/gcp/compute/gcp_compute_reservation.go
- extension/gcp/compute/gcp_compute_route.go
- extension/gcp/compute/gcp_compute_router.go
- extension/gcp/compute/gcp_compute_vpn_gateway.go
- extension/gcp/compute/gcp_compute_vpn_tunnel.go
- extension/gcp/container/gcp_container_cluster.go
- extension/gcp/dns/gcp_dns_managed_zone.go
- extension/gcp/dns/gcp_dns_policy.go
- extension/gcp/file/gcp_file_backup.go
- extension/gcp/file/gcp_file_instance.go
- extension/gcp/function/gcp_cloud_function.go
- extension/gcp/iam/gcp_iam_role.go
- extension/gcp/iam/gcp_iam_service_account.go
- extension/gcp/run/gcp_cloud_run_revision.go
- extension/gcp/run/gcp_cloud_run_service.go
- extension/gcp/sql/gcp_sql_database.go
- extension/gcp/sql/gcp_sql_instance.go
- extension/gcp/storage/gcp_storage_bucket.go
- extension/helper.go
- extension_config.json
- utilities/extension_configuration.go
Build docker image with basequery
For GCP, read projectID config property when shared credentials (which usually have projectID) are not set
NA
Tested locally with dockeri
> Build docker image with basequery and some GCP config changes

- Dockerfile
- extension/aws/kms/aws_kms_key.go
- extension/aws/kms/aws_kms_keys.go
- extension/aws/kms/table_config.json
- extension/aws/kms/tables.md
- extension/aws/tables.md
- extension/helper.go
aws_kms_key table added to cloudquery
> aws kms key table ported to cloudquery

- extension/aws/s3_glacier/aws_s3_glacier.go
- extension/aws/s3_glacier/aws_s3_glacier_vault.go
- extension/aws/s3_glacier/table_config.json
- extension/aws/s3_glacier/tables.md
- extension/helper.go
- extension/plugins.go
aws s3-glacier table added to cloudquery.
> s3-glacier added to cloudquery

- Dockerfile
- extension/aws/sns/aws_sns_topic.go
- extension/aws/sns/table_config.json
- extension/aws/sns/tables.md
- extension/aws/tables.md
- extension/plugins.go
aws sns-table added to cloudquery
> sns table added

- Dockerfile
- extension/aws/sqs/aws_sqs_queue.go
- extension/aws/sqs/table_config.json
- extension/aws/sqs/tables.md
- extension/aws/tables.md
- extension/plugins.go
aws sqs table added to cloudquery
> sqs table added

- extension/aws/cloudtrail/table_config.json
Restore cloudtrail events table
Tested using osqueryi
> - Restore cloudtrail events table

- Dockerfile
- extension/azure/cosmosdb/azure_cosmosdb_account.go
- extension/azure/cosmosdb/table_config.json
- extension/azure/cosmosdb/tables.md
- extension/azure/tables.md
- extension/plugins.go
Added Azure CosmosdbAccount table to cloudquery
https://github.com/Azure/azure-sdk-for-go/tree/main/services/cosmos-db/mgmt/2021-10-15/documentdb
Tested using osqueryi ,all the enabled attributes are shown with resp values …
> Azure cosmosdb account

- Dockerfile
- extension/azure/postgresql/azure_postgresql_server.go
- extension/azure/postgresql/table_config.json
- extension/azure/postgresql/tables.md
- extension/azure/tables.md
- extension/plugins.go
Added azure_postgresql_server table to cloudquery
https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v60.1.0+incompatible/services/postgresql/mgmt/2020-01-01/postgresql
Tested using osqueryi,all data fetched currectly.
Describe …
> Azure postgresql server

- Dockerfile
- extension/azure/sql/azure_sql_server.go
- extension/azure/sql/table_config.json
- extension/azure/sql/tables.md
- extension/azure/tables.md
- extension/plugins.go
- go.mod
- Azure SQL server table is added
- table config and plugins file are modified to accommodate the new table
- SQL folder is added to the docker file keeping everything 
- https://github.com/Azure/azure-sdk-for-go/tree/main/services
- https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v60.0.0+incompatible/services/sql/mgmt/2014-04-01/sql?utm_source=gopls
- using OSqueryI
> Azure sql server

- Dockerfile
- extension/azure/keyvault/azure_keyvault_vault.go
- extension/azure/keyvault/table_config.json
- extension/azure/keyvault/tables.md
- extension/azure/tables.md
- extension/plugins.go
- go.mod
- go.sum
Added azure_keyvault_vault relation and made respective changes
github.com/Azure/azure-sdk-for-go/services/keyvault/mgmt/2019-09-01/keyvault
Tested on osqueryi with local device
> Azure keyvault vault

- Dockerfile
- extension/azure/cosmosdb/azure_cosmosdb_mongodb.go
- extension/azure/cosmosdb/table_config.json
- extension/azure/cosmosdb/tables.md
- extension/azure/tables.md
- extension/plugins.go
Added azure_cosmosdb_mongodb relation and made respective changes in plugins,tables.md,dockerfile
https://github.com/Azure/azure-sdk-for-go/blob/main/services/cosmos-db/mgmt/2021-10-15/documentdb
Tested with osquery on local device
> Azure cosmosdb mongodb

- Dockerfile
- extension/azure/keyvault/azure_keyvault_key.go
- extension/azure/keyvault/table_config.json
- extension/azure/keyvault/tables.md
- extension/azure/tables.md
- extension/plugins.go
Added azure_keyvault_key and made respective changes
"github.com/Azure/azure-sdk-for-go/services/keyvault/mgmt/2019-09-01/keyvault"
Tested with osqueryi on local device
> Azure keyvault key

- Dockerfile
- extension/azure/containerservice/azure_containerservice_managed_cluster.go
- extension/azure/containerservice/table_config.json
- extension/azure/containerservice/tables.md
- extension/azure/tables.md
- extension/plugins.go
Added azure_containerservice_managed_cluster table to cloudquery
github.com/Azure/azure-sdk-for-go@v60.1.0+incompatible/services/containerservice/mgmt/2021-10-01/containerservice
Tested using osqueryi
Describe the testing done. …
> Azure containerservice managed cluster

- extension/azure/securitycenter/azure_securitycenter_setting.go
- extension/azure/securitycenter/table_config.json
- extension/azure/securitycenter/tables.md
- extension/azure/tables.md
- extension/plugins.go
Added azure_securitycenter_setting table to cloudquery
Tested using osqueryi.
> Azure securitycenter setting

- extension/azure/securitycenter/azure_securitycenter_subscription_pricing.go
- extension/azure/securitycenter/table_config.json
- extension/azure/securitycenter/tables.md
- extension/azure/tables.md
- extension/plugins.go
added azure_securitycenter_subscription_pricing table cloudquery
Tested using osqueryi..
> Azure securitycenter subscription pricing

- extension/azure/securitycenter/azure_seuritycenter_auto_provisioning.go
- extension/azure/securitycenter/table_config.json
- extension/azure/securitycenter/tables.md
- extension/azure/tables.md
- extension/plugins.go
added azure_securitycenter_auto_provisioning table to cloudquery
Tested using osqueryi...
> Azure securitycenter auto provisioning

- extension/azure/network/azure_network_load_balancer.go
- extension/azure/network/azure_network_watcher_flow_log.go
- extension/azure/network/table_config.json
- extension/azure/network/tables.md
- extension/azure/tables.md
- extension/plugins.go
Added azure_network_load_balancer relation and made respective changes
https://github.com/Azure/azure-sdk-for-go
Tested with osquery on local device
> added azure_network_load_balancer

- Dockerfile
- extension/azure/graphrbac/azure_graphrbac_user.go
- extension/azure/graphrbac/table_config.json
- extension/azure/tables.md
- extension/plugins.go
Added azure_graphrbac_user relation
https://github.com/Azure/azure-sdk-for-go
Tested with osquery on local device
> Azure graphrbac user

- extension/azure/graphrbac/azure_graphrbac_group.go
- extension/azure/graphrbac/table_config.json
- extension/azure/graphrbac/tables.md
- extension/azure/tables.md
- extension/plugins.go
Added azure_graphrbac_group to cloudquerry
Tested using Osqueryi..
> Azure graphrbac group
